apiVersion: v1 
kind: pod 
metadata:
  name: annotationpod
  annotations:
    owner: "sangam "
    notificatin-email: "owner@email.com"
    realesedate: "1.1.2022"
    ngnix.ingress.kubenetes.io/force-ssl-redirect: "true"
spec:
   containers:
     - name: annotationcontainer
       image: ngnix:latest 
       ports:
         - containerPort: 80
       env: 
         - name: USER
           value: "username"  


           