apiVersion: v1 
kind: pod 
metadata:
  name: firstpod
  labels:
    app: frontend 
    tier: frontend
    mycluster.local/team: team1 
spec:
   containers:
     - name: ngnix 
       image: ngnix:latest 
       ports:
         - containerPort: 80
       env: 
         - name: USER
           value: "username"  


           